# Generated by Django 5.1.3 on 2024-11-29 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolepermission',
            old_name='create_permission',
            new_name='create_access',
        ),
        migrations.RenameField(
            model_name='rolepermission',
            old_name='delete_permission',
            new_name='delete_access',
        ),
        migrations.RenameField(
            model_name='rolepermission',
            old_name='update_permission',
            new_name='update_access',
        ),
        migrations.RenameField(
            model_name='rolepermission',
            old_name='view_permission',
            new_name='view_access',
        ),
    ]
