# Generated by Django 5.1.3 on 2024-12-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_rename_create_permission_rolepermission_create_access_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivity',
            old_name='activity',
            new_name='action_type',
        ),
        migrations.RenameField(
            model_name='useractivity',
            old_name='time_stamp',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='email',
            field=models.EmailField(default='salma.razzaq@alchemative.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useractivity',
            name='full_name',
            field=models.CharField(default='Salma Razzaq', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.0'),
            preserve_default=False,
        ),
    ]
