# Generated by Django 5.1.3 on 2024-12-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_passwordresettoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
